# Site settings
title: Natalia Baltazar
email: natalialeebaltazar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Natalia Baltazar's personal site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nataliabaltazar.me" # the base hostname & protocol for your site
twitter_username: NataliaLKB
github_username:  NataliaLKB

# Build settings
markdown: kramdown
